customers/urls.py
from django.urls import path
from accounts import views as AccountViews
from . import views


urlpatterns = [
    path('', AccountViews.CustDashboard.as_view(), name='customer'),
    path('profile/', views.CProfileView.as_view(), name='cprofile'),
    path('my-orders/', views.MyOrdersView.as_view(), name='my_orders'),
    path('order/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('vendor/orders/', views.VendorOrdersView.as_view(), name='vendor_orders'),
    path('vendor/orders/<int:pk>/', views.VendorOrderDetailView.as_view(), name='vendor_order_detail'),
]

foodOnline_main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from marketplace import views as MarketplaceViews
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.Home.as_view(), name="home"),
    path("", include("accounts.urls")),
    path("marketplace/", include("marketplace.urls")),
    # CART
    path("cart/", MarketplaceViews.Cart.as_view(), name="cart"),
    # SEARCH
    path('search/', MarketplaceViews.Search.as_view(), name='search'),
    path('checkout/', MarketplaceViews.CheckoutView.as_view(), name='checkout'),
    # ORDERS
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from orders.views import StripeConfig
from .views import CreateCheckoutSession

urlpatterns = [
    path('place-order/', views.PlaceOrderView.as_view(), name='place_order'),
    path('config/', StripeConfig.as_view(), name='stripe_config'),
    path('create-checkout-session/', CreateCheckoutSession.as_view(), name='create_checkout_session'),
    path('successed/', views.SuccessView.as_view()), # new
    path('cancelled/', views.CancelledView.as_view()), # new
    path('webhook/stripe/', views.StripeWeebhook.as_view())
]

customers/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from accounts.models import User
from menu.models import FoodItem
from vendor.models import Vendor


class Payment(models.Model):
    PAYMENT_METHOD = (
        ('PayPal', 'PayPal'),
        ('RazorPay', 'RazorPay'), # Only for Indian.
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    payment_method = models.CharField(choices=PAYMENT_METHOD, max_length=100)
    amount = models.CharField(max_length=10)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.transaction_id
    

class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=15, blank=True)
    state = models.CharField(max_length=15, blank=True)
    city = models.CharField(max_length=50)
    pin_code = models.CharField(max_length=10)
    total = models.FloatField()
    tax_data = models.JSONField(blank=True, help_text = "Data format: {'tax_type':{'tax_percentage':'tax_amount'}}")
    total_tax = models.FloatField()
    payment_method = models.CharField(max_length=25)
    status = models.CharField(max_length=15, choices=STATUS, default='New')
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    # New field to link to Vendor
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True)

    # Concatenate first name and last name
    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'
    
    def __str__(self):
        return self.order_number
    

class OrderedFood(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fooditem = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # New field to link to Vendor
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.fooditem.food_title

customers/views.py
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404
from django.views.generic import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from accounts.forms import UserInfoForm, UserProfileForm
from accounts.models import UserProfile
from orders.models import Order, OrderedFood
from django.views.generic import ListView, DetailView


class CProfileView(LoginRequiredMixin, UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'customers/cprofile.html'
    success_url = reverse_lazy('cprofile')

    def get_object(self):
        # Get the UserProfile for the logged-in user
        return get_object_or_404(UserProfile, user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_form'] = UserInfoForm(instance=self.request.user)
        return context

    def form_valid(self, form):
        user_form = UserInfoForm(self.request.POST, instance=self.request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(self.request, 'Profile updated successfully!')
            return super().form_valid(form)
        else:
            return self.form_invalid(form)

    def form_invalid(self, form):
        context = self.get_context_data()
        context['user_form'] = UserInfoForm(instance=self.request.user)
        return self.render_to_response(context)


class MyOrdersView(ListView):
    model = Order
    template_name = 'customers/my_orders.html'  
    context_object_name = 'orders'  # The context variable to use in the template

    def get_queryset(self):
        # Filter the orders for the current user and only those that are ordered
        return Order.objects.filter(user=self.request.user, is_ordered=True).order_by('-created_at')
    

class OrderDetailView(DetailView):
    model = Order
    template_name = 'customers/order_detail.html'  
    context_object_name = 'order'  

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class VendorOrdersView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'vendor/vendor_orders.html'
    context_object_name = 'orders'
    login_url = 'login'

    def get_queryset(self):
        # Fetch the current vendor
        current_vendor = self.request.user.user  # Assuming the user has a OneToOne relationship with Vendor
        return Order.objects.filter(vendor=current_vendor).order_by('-created_at')

    def get_context_data(self, **kwargs):
        # Add vendor information to the context
        context = super().get_context_data(**kwargs)
        context['vendor'] = self.request.user.user  # Assuming user has OneToOne relation with Vendor
        return context
    

class VendorOrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    template_name =  'vendor/vendor_order_detail.html'
    context_object_name = 'order'
    login_url = 'login'

    def get_queryset(self):
        current_vendor = self.request.user.user
        return Order.objects.filter(vendor=current_vendor)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ordered_food_items'] = OrderedFood.objects.filter(order=self.object)
        return context

templates/customers/cover.html
{% load static %}
<div class="page-section restaurant-detail-image-section" style=" background: url({% if user_profile.cover_photo %}{{ user_profile.cover_photo.url }} {% else %} {% static 'images/default-cover.png' %} {% endif %} ) no-repeat scroll 0 0 / cover;">
    <!-- Container Start -->
    <div class="container">
        <!-- Row Start -->
        <div class="row">
            <!-- Column Start -->
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="company-info-detail">
                    <div class="company-info">
                        <div class="img-holder">
                            <figure>
                                {% if user_profile.profile_picture %}
                                <img src="{{ user_profile.profile_picture.url }}" alt="Profile Picture">
                                {% else %}
                                <img src="{% static 'extra-images/listing-logo18.png' %}" alt="">
                                {% endif %}
                            </figure>
                        </div>
                        <div class="text-holder">
                            <span class="restaurant-title">{{ user.first_name }} {{ user.last_name }}</span>
                            <div class="text">
                                <i class="icon-location"></i>
                                <p>{{ user.phone_number }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Column End -->
        </div>
        <!-- Row End -->
    </div>
    <!-- Container End -->
</div>

templates/customers/cprofile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'includes/alerts.html' %}
<div class="main-section">
    {% include 'customers/cover.html' %}
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    {% include 'includes/c_sidebar.html' %}
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            <h5 class="text-uppercase">Profile Settings</h5>
                            <form action="{% url 'cprofile' %}" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-fields-set">
                                    <ul>
                                        <li>
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="restaurant-info">
                                                        <label>Update Profile Picture</label>
                                                        <div class="upload-gallery">
                                                            {{ form.profile_picture }}
                                                            {% if profile_form.profile_picture.errors %}
                                                                <span class="text-danger">{{ profile_form.profile_picture.errors }}</span>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-lg-12">
                                                    <div class="restaurant-info">
                                                        <label>Update Cover Photo</label>
                                                        <div class="upload-gallery">
                                                            {{ form.cover_photo }}
                                                            {% if profile_form.cover_photo.errors %}
                                                                <span class="text-danger">{{ profile_form.cover_photo.errors }}</span>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-lg-6">
                                                    <div class="field-holder">
                                                        <label>First Name *</label>
                                                        {{ user_form.first_name }}
                                                    </div>
                                                </div>
                                                <div class="col-lg-6">
                                                    <div class="field-holder">
                                                        <label>Last Name *</label>
                                                        {{ user_form.last_name }}
                                                    </div>
                                                </div>
                                                <div class="col-lg-6">
                                                    <div class="field-holder">
                                                        <label>Phone Number *</label>
                                                        {{ user_form.phone_number }}
                                                    </div>
                                                </div>
                                                <div class="col-lg-12">
                                                    <div class="field-holder">
                                                        <label>Address *</label>
                                                        {{ form.address }}
                                                        <small class="text-muted float-right">powered by Google</small>
                                                    </div>
                                                </div>

                                                <div class="col-lg-6">
                                                    <div class="field-holder">
                                                        <label>Country *</label>
                                                        {{ form.country }}
                                                    </div>
                                                </div>
                                                <div class="col-lg-6">
                                                    <div class="field-holder">
                                                        <label>State *</label>
                                                        {{ form.state }}
                                                    </div>
                                                </div>
                                                <div class="col-lg-6">
                                                    <div class="field-holder">
                                                        <label>City *</label>
                                                        {{ form.city }}
                                                    </div>
                                                </div>
                                                <div class="col-lg-6">
                                                    <div class="field-holder">
                                                        <label>Pin Code *</label>
                                                        {{ form.pin_code }}
                                                    </div>
                                                </div>
                                                <div class="col-lg-6">
                                                    <div class="field-holder">
                                                        <label>Latitude *</label>
                                                        {{ form.latitude }}
                                                    </div>
                                                </div>
                                                <div class="col-lg-6">
                                                    <div class="field-holder">
                                                        <label>Longitude *</label>
                                                        {{ form.longitude }}
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                    <div>
                                        <input type="submit" value="Update Profile">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/customers/my_orders.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'includes/alerts.html' %}

<!-- Main Section Start -->
<div class="main-section">
    {% include 'customers/cover.html' %}
    <div class="page-section account-header buyer-logged-in">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                    <!-- Load the sidebar here -->
                    {% include 'includes/c_sidebar.html' %}
                </div>
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                    <div class="user-dashboard loader-holder">
                        <div class="user-holder">
                            
                            <h5 class="text-uppercase">My Orders</h5>
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="user-orders-list">
                                        <div class="responsive-table">
                                            <table class="table table-hover">
                                                <thead>
                                                  <tr>
                                                    <th scope="col">Order Number</th>
                                                    <th scope="col">Name</th>
                                                    <th scope="col">Total</th>
                                                    <th scope="col">Status</th>
                                                    <th scope="col">Date</th>
                                                    <th scope="col">Action</th>
                                                  </tr>
                                                </thead>
                                                <tbody>
                                                    {% for order in orders %}
                                                  <tr>
                                                    <td>{{ order.order_number }}</td>
                                                    <td>{{ order.name }}</td>
                                                    <td>${{ order.total }}</td>
                                                    <td>{{ order.status }}</td>
                                                    <td>{{ order.created_at }}</td>
                                                    <td><a href="{% url 'order_detail' order.id %}" class="btn btn-danger">Details</a></td>
                                                  </tr>
                                                  {% empty %}
                                                  <tr>
                                                    <td colspan="6" class="text-center">No orders found.</td>
                                                  </tr>
                                                  {% endfor %}
                                                </tbody>
                                              </table>
                                        </div>												
                                    </div>
                                </div>												
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Section End -->

{% endblock %}

templates/customers/order_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2>Order Details</h2>
    <div class="order-details">
        <h4>Order Number: {{ order.order_number }}</h4>
        <p><strong>Name:</strong> {{ order.name }}</p>
        <p><strong>Email:</strong> {{ order.email }}</p>
        <p><strong>Phone:</strong> {{ order.phone }}</p>
        <p><strong>Address:</strong> {{ order.address }}, {{ order.city }}, {{ order.state }}, {{ order.country }}, {{ order.pin_code }}</p>
        <p><strong>Total Amount:</strong> ${{ order.total }}</p>
        <p><strong>Status:</strong> {{ order.get_status_display }}</p>
        <p><strong>Payment Method:</strong> {{ order.payment_method }}</p>
        <h4>Ordered Items</h4>
        <ul>
            {% for item in order.orderedfood_set.all %}
                <li>{{ item.fooditem.food_title }} - Quantity: {{ item.quantity }} - Price: ${{ item.price }} - Amount: ${{ item.amount }}</li>
            {% empty %}
                <li>No items found in this order.</li>
            {% endfor %}
        </ul>
        <p><strong>Order Date:</strong> {{ order.created_at }}</p>
    </div>
    <a href="{% url 'my_orders' %}" class="btn btn-primary">Back to My Orders</a>
</div>
{% endblock %}