foodOnline_main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from marketplace import views as MarketplaceViews
from . import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.Home.as_view(), name="home"),
    path("", include("accounts.urls")),
    path("marketplace/", include("marketplace.urls")),
    # CART
    path("cart/", MarketplaceViews.Cart.as_view(), name="cart"),
    # SEARCH
    path('search/', MarketplaceViews.Search.as_view(), name='search'),
    path('checkout/', MarketplaceViews.CheckoutView.as_view(), name='checkout'),
    # ORDERS
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views
from orders.views import StripeConfig
from .views import CreateCheckoutSession

urlpatterns = [
    path('place-order/', views.PlaceOrderView.as_view(), name='place_order'),
    path('config/', StripeConfig.as_view(), name='stripe_config'),
    path('create-checkout-session/', CreateCheckoutSession.as_view(), name='create_checkout_session'),
    path('successed/', views.SuccessView.as_view()), # new
    path('cancelled/', views.CancelledView.as_view()), # new
    path('webhook/stripe/', views.StripeWeebhook.as_view())
]

orders/models.py
from django.db import models
from accounts.models import User
from menu.models import FoodItem
from vendor.models import Vendor


class Payment(models.Model):
    PAYMENT_METHOD = (
        ('PayPal', 'PayPal'),
        ('RazorPay', 'RazorPay'), # Only for Indian.
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    payment_method = models.CharField(choices=PAYMENT_METHOD, max_length=100)
    amount = models.CharField(max_length=10)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.transaction_id
    

class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=15, blank=True)
    state = models.CharField(max_length=15, blank=True)
    city = models.CharField(max_length=50)
    pin_code = models.CharField(max_length=10)
    total = models.FloatField()
    tax_data = models.JSONField(blank=True, help_text = "Data format: {'tax_type':{'tax_percentage':'tax_amount'}}")
    total_tax = models.FloatField()
    payment_method = models.CharField(max_length=25)
    status = models.CharField(max_length=15, choices=STATUS, default='New')
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    # New field to link to Vendor
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True)

    # Concatenate first name and last name
    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'
    
    def __str__(self):
        return self.order_number
    

class OrderedFood(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fooditem = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # New field to link to Vendor
    vendor = models.ForeignKey(Vendor, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.fooditem.food_title

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>FoodOnline</title>
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	<!-- CSS -->
	<link href="{% static 'css/iconmoon.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="{% static 'css/bootstrap-slider.css' %}" rel="stylesheet">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- JAVASCRIPT -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static 'js/modernizr.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>

	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	{% if '/profile/' in request.GET %}
	<script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete" async defer></script>
	{% endif %}
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	<script src="{% static 'js/custom.js' %}"></script>
	<script src="https://js.stripe.com/v3/"></script>
	
	

	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}
	</style>
</head>

<body>

    <!-- LOAD NAVBAR HERE -->
    {% include 'includes/navbar.html' %}

    <!-- LOAD CONTENT HERE -->
    {% block content %}
        <!-- CONTENT GOES HERE -->
    {% endblock %}

    <!-- LOAD FOOTER HERE -->
    {% include 'includes/footer.html' %}

templates/cancelled.html
{% extends "base.html" %}
{% load static %}

{% block content %}
      <p>Your payment is cancelled.</p>


{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<body>
	
		<!-- Main Section Start -->
		<div class="main-section">
			<!-- Home Pages Elements Strat -->
			<!-- Main Search Start -->
			<div class="page-section nopadding cs-nomargin" style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url({% static 'extra-images/bg-image1.jpg' %}) no-repeat center / cover;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="element-title">
								<h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
									We are in the business of food<br>our restaurants do</h1>
								<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
									Ridiculus sociosqu
									cursus neque cursus curae ante scelerisque vehicula.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="main-search fancy bg-holder">
								<form action="{% url 'search' %}"  method="GET">
									<div class="row">
										<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
											<div class="field-holder">
												<input type="text" name="keyword" placeholder="Resturant name or food name">
											</div>
										</div>
										<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
											<div class="field-holder">
												<ul>
													<li class="select-location">
														<div class="foodbakery-locations-fields-group foodbakery-focus-out">
															<span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
														    	<input type="text" name="address" class="location-field-text filter" id="id_address" required placeholder="All Locations">
															</div>
														</div>
													</li>
												</ul>
											</div>
										</div>
										<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
											<div class="field-holder">
												<input type="submit" value="Search">
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>

					</div>
				</div>
			</div>
			<!-- Main Search End -->

			<!-- Top Restarurants Section Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-left">
								<h2>Top Restaurants</h2>
								<p>Explore restaurants, bars, and cafés by locality</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="company-logo">
								<ul>
									{% for vendor in vendors %}
									<li class="has-border">
										<figure>
									{% if vendor.user_profile.profile_picture %}
									<a href="#"><img src="{{ vendor.user_profile.profile_picture.url }}" class="attachment-full size-full wp-post-image" alt=""></a>
									{% else %}
									<a href="#"><img src="{% static 'images/default-profile.png' %}" class="attachment-full size-full wp-post-image" alt=""></a>
									{% endif %}

										</figure>
										{% endfor %}
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Top Restarurants Section End -->
			<!-- Choose From Most Popular Listin Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-center">
								<h2>Choose From Most Popular Restaurants</h2>
								<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="listing fancy">
								<ul class="row">
									{% for vendor in vendors %}
		
									<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
										<div class="list-post featured">
											<div class="img-holder"></div>
												<figure>
													<a href="#">
														{% if vendor.user_profile.profile_picture %}
														<img src="{{ vendor.user_profile.profile_picture.url }}" class="img-thumb wp-post-image" alt="">
														{% else %}
														<img src="{% static 'images/default-profile.png' %}" class="img-thumb wp-post-image" alt="">
														{% endif %}
													</a>
												</figure>
												<span class="restaurant-status close">
													<em class="bookmarkRibbon"></em>Close
												</span>
											</div>
											<div class="text-holder">
												
												<div class="post-title">
													<h5>
														<a href="listing-detail.html">{{ vendor }}</a>
						
													</h5>
												</div>
												{% if vendor.user_profile.city and vendor.user_profile.state and vendor.user_profile.pin_code %}
												<span>{{ vendor.user_profile.city }}, {{ vendor.user_profile.state }}, {{ vendor.user_profile.pin_code }}</span>
												{% endif %}
													
											</div>
											<div class="list-option">
												<a href="javascript:void(0);" class="shortlist-btn" data-toggle="modal" data-target="#sign-in">
												
										</div>
									</li>
									{% endfor %}

								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Choose From Most Popular Listing End -->

			
		</div>
		
</body>
{% endblock %}

templates/success.html
{% extends "base.html" %}
{% load static %}

{% block content %}
      <p>Your payment succeeded.</p>


{% endblock %}